### ISSUE TITLE
Can't run script..

### ISSUE THREAD

**Issue by mkl-strnge** [alexsteb/GuitarPro-to-Midi#1]
Hi! I need to convert > 1000 gp files in bulk, and your script is the only tool that I found in the whole fking internet =) Could you please specify how to run it, I never used Unity and can't understand what I'm doing wrong. I imported the file, nothing happens with Run button, when I try to Build & Run - log is full of errors. 

![2019-03-02_122953](https://user-images.githubusercontent.com/48006264/53680801-e85d0400-3ce8-11e9-8722-faa33d16e1f4.jpg)

**Comment by alexsteb** [comment]
Hi, thank you for trying out my program.
Unfortunately I don't have the time to remotely diagnose your issues there.
You can either try downloading and installing some other (older / newer) Unity versions or Googling that error message "System.Windows.Forms" etc.
My quick google showed that it might have something to do with the set .NET version.
But try out for yourself!

Cheers
