### ISSUE TITLE
Export from Gp file to Midi in Console Application

### ISSUE THREAD

**Issue by hd-i** [alexsteb/GuitarPro-to-Midi#5]
Hello. How are you.
How can I Export from Guitar Pro file to Midi file in  C# Console Application ?
Thanks.

**Comment by sasualx** [comment]
Hey, It seems that the original author does not follow this repository anymore. I made some changes that can make this program runnable from the terminal and I have created a pull request https://github.com/alexsteb/GuitarPro-to-Midi/pull/3 . If you follow the steps there you can just convert any gp file from the terminal. Hope it helps.

**Comment by hd-i** [comment]
Thanks.
